### ISSUE TITLE
Operation parameters are not present in openapi file

### ISSUE THREAD

**Issue by ph-kaelin** [youengineering/openapi-maven-plugin#2]
Hey Carl, it's me, Philipp from Swisscom :-)

I'm not sure but I think there is a problem when generating the openapi file.
I add parameters in the @Operation annotation but they don't show up in the output file (openapi.yaml).

```
@Operation(description = "...",
            parameters = {
                    @Parameter(in = ParameterIn.HEADER, name = "forwarded", description = "...")
            }
)
```

Could you please have a look, thanks!
Cheers, Philipp

**Comment by carlkuesters** [comment]
Hi Philipp,

thanks for the info, sorry I didn't see this issue earlier - I can confirm this is a bug in the plugin.
I reproduced it with the following testcase:

```
@RestController
@RequestMapping(value = "/parameters")
public class TestParametersController {

    @PostMapping("/annotationOperationParameter")
    @Operation(description = "...", parameters = { @Parameter(in = ParameterIn.HEADER, name = "myName", description = "myName") } )
    public void testAnnotationOperationParameter() {

    }
}
```
Which produces no parameters:
```
  /parameters/annotationOperationParameter:
    post:
      summary: ""
      description: '...'
      operationId: TestParametersController_testAnnotationOperationParameter_post
      responses:
        default:
          description: successful operation
      security: []
```

I will keep this ticket up to date and add the case above to the automated tests once fixed. :)

**Comment by carlkuesters** [comment]
Hi Philipp,

I released version **0.0.8** with an according fix, please let me know if it works for you.
Hint: It might take 1 or 2 hours until the plugin is synced to the Maven central repo.

Regards,
Carl

P.S.: On your side, the version is defined in RawOpenAPIGenerator.java - You can adjust it there locally, change the version of the apigee-plugin to a new "candidate" version (e.g. just increasing the patch version), and then do "mvn clean install", which installs your locally-changed-plugin to your local-maven-folder. Then you can set the version in a MiSe locally to said candidate plugin version and do a Maven build locally to see the target/openapi/openapi.yaml file. Meaning you can do all this and verify the result without pushing or releasing the apigee maven plugin. To make sure it works before releasing a new version.

**Comment by ph-kaelin** [comment]
It works!
Thanks a lot for the super fast fix :-)

so I will release the oce-apigee-maven-plugin with the new 0.0.8 version, right?

**Comment by carlkuesters** [comment]
Exactly. We didn't have time to setup an automated pipeline for it, so you have to do it manually at the moment ("mvn clean deploy" (ideally from the master branch after pushing it) with a user that has the permissions to deploy to artifactory). I think Gianluca Caldari from Team Atlas did this recently in the last weeks, he might be able to give you tips if you face any problems. And I recommend adding a git tag to the latest master commit then, just for documentation purposes, they don't have any effect, but it's useful to see which is the latest version from the commits overview in git.

I will close this ticket for now, but feel free to create new ones if any problems occur or if you have questions. I'm also always available via carl.kuesters@youengineering.ch and happy to help 👍
