### ISSUE TITLE
Frage: Wie kann ich einen "Type" unter "components:schemas" hinzufügen?

### ISSUE THREAD

**Issue by ph-kaelin** [youengineering/openapi-maven-plugin#3]
Ich möchte der generierten Swagger-Datei (openapi.yml) unter components: schemas: einen Type hinzufügen.
Wie kann ich das machen?
Danke und Gruss, Philipp Kälin

**Comment by carlkuesters** [comment]
Hallo Philipp,

habe die Frage erst jetzt gesehen - Aus was für einem Grund soll dort ein Type geaddet werden? Ist es ein Type, der in der API gar nicht benutzt wird? Oder gibt es Probleme bei einem Endpunkt, dass der Typ "geinlined" wird statt unten definiert&referenziert zu sein?

Falls es ein Type ist, der gar nicht benutzt wird, gibt es solch eine Funktion noch nicht. Könnte man sicher hinzufügen, dass man dem Plugin eine Liste an Classnames mitgeben kann, die aufgeführt werden, aber ich frage mich was der Grund ist.

Grüsse,
Carl

**Comment by carlkuesters** [comment]
Ich werde dieses Issue schließen, ich gehe davon aus dass sich die Thematik geklärt/gelöst hat. Ansonsten einfach wieder aufmachen :)

**Comment by ph-kaelin** [comment]
Sorry, ich hatte den Issue vergessen. Merci
