### ISSUE TITLE
Swagger documentation for embedded DTOs missing

### ISSUE THREAD

**Issue by tfo** [youengineering/openapi-maven-plugin#4]
Hi guys,
I'm from Swisscom and noticed problem with the _openapi-maven-plugin_ for Swagger 3. Some of our REST endpoints return not only a responses with a simple DTO or a list of DTOs, but some with more structure. All these DTOs are properly linked together and also annotated with the necessary Swagger 3 annotations. Unfortunately the Swagger documentation that is returns afterwards tells me that some of the schemes are not available and these are exactly the ones that would belong to the linked DTOs.

_Could not resolve reference: Could not resolve pointer: /components/schemas/LinkDto does not exist in document_

Let me give me you a quick example:

```java
@Schema(description = "Defines a paged slice of entries with the my data.")
public class SliceDto {

	@ArraySchema(
			schema = @Schema(
					description = "The list of the entries with the my data.",
					required = true)
	)
	private final List<MyDto> content;

	@Schema(description = "The number of the page/slice that was requested.",
			example = "1",
			required = true)
	private final int page;

	@Schema(description = "The size of the page/slice that was requested.",
			example = "20",
			required = true)
	private final int size;

	@Schema(description = "The number of results in this page/slice.",
			example = "5",
			required = true)
	private final int numberResults;

	@ArraySchema(
			schema = @Schema(
					description = "The list of the links to the previous, self and next page/slice.",
					required = true)
	)
	private final List<LinkDto> links;
}

@Schema(description = "Defines link definition for a page/slice.")
public class LinkDto {

	@Schema(description = "The name of the link that is delivered. Available are the links to the previous, self and next page/slice.",
			example = "self",
			allowableValues = {"prev", "self", "next"},
			required = true)
	private final String rel;

	@Schema(description = "The link to the resource that is delivered.",
			example = "http://www.mydomain.com/my-resource?page=0&size=20",
			required = true)
	private final String href;
}`

@RestController
@RequestMapping("/my-resource")
public class MyRestController {

	...
	@GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
	@Operation(
			summary = "Loads the my data ...",
			method = "GET",
			responses = {
					@ApiResponse(
							responseCode = "200",
							description = "Returns a page of the my data...",
							content = @Content(
									mediaType = MediaType.APPLICATION_JSON_VALUE,
									schema = @Schema(implementation = SliceDto.class))
					),
					...
			}
	)
	public ResponseEntity<SliceDto> getMyData() {
		...
	}
}
```

With a structure of the DTOs like this the Swagger documentation is generated just for the REST controller and the SliceDto, but for example the schemes for MyDto and LinkDto are missing. So there is no entry in the existing yaml files nor specific yaml files for them.

```yaml
                  ...
                  links:
                    type: array
                    items:
                      $ref: '#/components/schemas/LinkDto'
                  ...
```

Is there a specific configuration needed to create the complete Swagger documentation or is that "feature" missing?

Thanks & Best,
Tobias

**Comment by carlkuesters** [comment]
Hi Tobias,

thanks for opening an issue and providing a test case. I will analyze it - Usually, the plugin should not have any problem with nested DTOs, so I assume it's just something small going wrong in the implementation.

I will keep you up-to-date in this ticket.

Best regards,
Carl

**Comment by carlkuesters** [comment]
So, I analyzed the issue and it's actually a problem I foresaw in the past.

In short: The "problem" is the "responses = { @ApiResponse(...) }" on the controller method. The way that the plugin currently works, is to first load the response definition from the annotation on the controller method. **If (and only if) it doesn't have one**, it generates it from the response class. So we have two ways that the code can go:
- The first way (via the annotation) currently does **not** support nested DTOs (yet)
- The second way (via the response class without @ApiResponse annotation on the controller method) does support nested DTOs

In the end, both are using the same utilities, so it would totally be a doable enhancement (or better said: fix) of the plugin to support all of this correctly. It just wasn't done so far yet. I just wanted to explain where the bug is.

That said, I will fix the bug and make sure that nesting is also supported when using the @ApiResponse annotation on the controller method.

In the meantime, you can remove the @ApiResponse annotation in your code (until the new version is ready) in case you are blocked otherwise.

Please let me know if this is fine for you.

**Comment by tfo** [comment]
Hi Carl,

Thanks for your investigations. I just tried it out without the _@ApiResponse_ annotation. Now it works. Basically for us it's not a blocking issue, so we can easily wait for a fix of the _openapi-maven-plugin_, but for sure I will share your insights in our teams.

Just let us know when the new version is available.

Thanks & Best,
Tobias

**Comment by carlkuesters** [comment]
Hi Tobias,

I finally had time this morning to fix the issue. I fixed the bug in commit 474f212 and released a new version **0.0.9**, which should be available at any moment in your artifactory (via Maven central repo).
The new version ensures that all referenced schemas (nested DTOs) that are parsed via annotation, are correctly included in the components section, this includes also other cases like header or parameter annotations, which would have had the same problem in the old version.

Thanks for reporting the bug with a test case and please let me know if the new version works fine on your end. And if you have any other issues with the plugin, always feel free to ask - I'm glad to help. :)

Best regards,
Carl

**Comment by tfo** [comment]
Hi Carl,

Thank you very much for that quick fix. We will check the fixed version and see if it solved the problem. If not, we will get back to you.

Thanks & Best,
Tobias

**Comment by carlkuesters** [comment]
I will close this issue now as it seems to be resolved :) If you encounter any other related problems, feel free to reopen it.
