### ISSUE TITLE
Add Some descirption for 200 ApiResponse instead of blank value

### ISSUE THREAD

**Issue by bhargavmummini** [youengineering/openapi-maven-plugin#5]
Currently for 200 responses an empty description is added.
https://github.com/youengineering/openapi-maven-plugin/blob/474f212a933495c9e2a356a809b468cff6dd1401/src/main/java/com/youengineering/openapi/document/reader/AbstractReader.java#L312
The works fine during the initial swagger creation (openapi.yaml).

But when we parse the swagger with OpenAPIV3Parser's, empty values are by default ignored (Due to [OpenAPIDeserializer.java](https://github.com/swagger-api/swagger-parser/blob/a5234f5e1d0d62c20aca53ad2b9024f563164541/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java#L2761)).
And the swagger generated after customization does not contains a description and throws error in swagger view due to missing description.

Suggestion is to added a default description for 200 response as well.

**Comment by carlkuesters** [comment]
Hi Bhargav,

I hope you are doing fine. Thanks for the report and the detailed analysis - Your explanation makes perfect sense, I will look into it tomorrow and release a new version with a default description.

Best regards,
Carl

**Comment by carlkuesters** [comment]
Hi Bgarhav,

I added a default description in commit 38c1d0424bd57ff7c255c369ed2b20245f6f70c7 and released a new version 0.0.10, which should be available at any moment in your artifactory (via Maven central repo).

The default description is currently "Successful operation" and it can be customized via the content.defaultSuccessfulOperationDescription configuration on the plugin.

Please let me know if the new version works fine for you or if you face any other problems. I also added some test cases for the last Swisscom issue (https://github.com/youengineering/openapi-maven-plugin/issues/4), which I didn't happen to push yet. :)

Best regards and thanks a lot for creating the issue with a detailed analysis,
Carl

**Comment by bhargavmummini** [comment]
Hi Carl
I am doing fine, Thanks.
Hope you are doing fine too!

Thanks a lot for the quick fix.

The description is now getting populated and the swagger after customization looks perfect now.
And thanks a lot for also for providing the option to customize the description!.
