### ISSUE TITLE
Support for java 17 records

### ISSUE THREAD

**Issue by bhargavmummini** [youengineering/openapi-maven-plugin#9]
We recently started to migrate our applications to Java 17.
When we started using records for APIs response, then the API response was only treated as an object.

Java Record:
```
public record HelloWelcome(@Schema(description = "Testing of Java 17") String test, boolean isLatest){
}
```

generated open API:
```
  /v17:
    post:
      operationId: Controller_hello_post
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
```
Expected OpenAPI:
```
  /v17:
    post:
      operationId: Controller_hello2_post
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  test:
                    type: string
                    description: "Testing of Java 17
                  isLatest:
                    type: boolean
```

I just did a quick analysis, even though [spring-core does not support java records yet](https://github.com/swagger-api/swagger-core/issues/3867), However an update of all the dependencies was able to read and map records into valid schemas.

Attaching the patch of the pom.xml for dependency update
[dependency_version_update.zip](https://github.com/youengineering/openapi-maven-plugin/files/9285429/dependency_version_update.zip)

**Comment by bhargavmummini** [comment]
Hi @carlkuesters, Hope you are doing good. Do you still plan to actively support this plug-in?
If required I can also make a pull request for the requested change.
edit: I just made a PR #10 , would be really great if you can review and release a new version as soon as possible.
Thanks & Best Regards,
Bhargav

**Comment by carlkuesters** [comment]
Hi @bhargavmummini,

I'm fine, I hope you too. Thanks a lot for the PR and all the dependency version numbers, it can be a pain checking which versions work together :) For the technical discussion, I suggest we (continue to) have all further technical comments in the PR.

Kind regards,
Carl

**Comment by carlkuesters** [comment]
Oh, I overlooked your question: "Do you still plan to actively support this plug-in?"

Yes, I am still supporting this plugin - But obviously, as you might know, it will be in my freetime and it will be primarily from a maintenance point of view. Therefore, my suggestion is to always keep Dominik Erni in the loop, just in case I either oversee something or if something is very critical.

But feel free to always reach out to me, I'm happy to help :)

**Comment by bhargavmummini** [comment]
@carlkuesters Thanks a lot for the Response
And thank you very much for the clarification on the support of this plugin.
Thanks again for the extended help.

**Comment by carlkuesters** [comment]
Hi @bhargavmummini,

the new version was released (see comments in the PR) - Please try it out once it's available in Maven Central and if you notice any issues, feel free to post them here.

Kind regards,
Carl

**Comment by bhargavmummini** [comment]
Works fine. Closing it
